# WP8 SDK Installer
# by Maxim Kouprianov <me@kc.vc>

# Gets filepath by id
def file(id, payloads)
  payloads.map{|p| p.file if p.id == id}.compact!.shift
end

def chain(payloads)
  # => Useless packages which are in the manifest.xml are commented
  # => Date: 26.10.2012, newer releases may vary
  #
  #system("start /wait msiexec.exe /i %s" % file('vs_preclean_WPexpress', payloads))
  #system("start /wait msiexec.exe /i %s" % file('Preparation_Uninstall', payloads))
  system("start /wait msiexec.exe /i %s" % file('vcRuntimeMinimum_x86', payloads))
  system("start /wait msiexec.exe /i %s" % file('vs_minshellcore', payloads))
  system("start /wait msiexec.exe /i %s" % file('vs_minshellinterop', payloads))
  system("start /wait msiexec.exe /i %s" % file('vs_minshellres', payloads))
  system("start /wait %s /i /passive" % file('ssceruntime_x86_msi', payloads))
  system("start /wait %s /i /passive" % file('ssceruntime_x64_msi', payloads))
  system("start /wait msiexec.exe /i %s" % file('vcRuntimeMinimum_x64', payloads))
  system("start /wait msiexec.exe /i %s" % file('vcRuntimeAdditional_x86', payloads))
  system("start /wait msiexec.exe /i %s" % file('vcRuntimeAdditional_x64', payloads))
  system("start /wait msiexec.exe /i %s" % file('vcRuntimeDebug_x86', payloads))
  system("start /wait msiexec.exe /i %s" % file('vcRuntimeDebug_x64', payloads))
  system("start /wait msiexec.exe /i %s" % file('wp_sdk', payloads))
#  system("start /wait msiexec.exe /i %s" % file('WP_Images', payloads))
  system("start /wait msiexec.exe /i %s" % file('XDE_Host', payloads))
  system("start /wait msiexec.exe /i %s" % file('WPexpress_coremsi', payloads))
  system("start /wait msiexec.exe /i %s" % file('WPexpress_resourcemsi', payloads))
  system("start /wait msiexec.exe /i %s" % file('tfs_objectmodel_x64', payloads))
  system("start /wait msiexec.exe /i %s" % file('tfs_objectmodel_x64_lang', payloads))
  system("start /wait msiexec.exe /i %s" % file('vs_teamExplorerCore', payloads))
  system("start /wait msiexec.exe /i %s" % file('vs_teamExplorerCoreRes', payloads))
  system("start /wait msiexec.exe /i %s" % file('vs_expbsln_x64_msi_73', payloads))
  system("start /wait msiexec.exe /i %s /passive" % file('VMExpress_XNA', payloads))
  system("start /wait msiexec.exe /i %s" % file('MobileTools_AddInCore', payloads))
  system("start /wait msiexec.exe /i %s" % file('MobileTools_AddInCoreres', payloads))
  system("start /wait msiexec.exe /i %s" % file('Windows_MetroMinSDK', payloads))
  system("start /wait msiexec.exe /i %s" % file('vc_compilercore', payloads))
  system("start /wait msiexec.exe /i %s" % file('vc_compilercoreres', payloads))
  system("start /wait msiexec.exe /i %s" % file('vc_CompilerCoreWP80', payloads))
  system("start /wait msiexec.exe /i %s" % file('vc_CompilerCoreResWP80', payloads))
  system("start /wait msiexec.exe /i %s" % file('vc_LibraryCoreWP80', payloads))
  system("start /wait msiexec.exe /i %s" % file('help3_vs_msi', payloads))
  system("start /wait msiexec.exe /i %s" % file('netfx_dtpmsi_1048', payloads))
  system("start /wait msiexec.exe /p %s" % file('netfx_dtpmsp_KB2504637', payloads))
  system("start /wait %s" % file('VMExpress_Dev10_DirectX', payloads))
  system("start /wait %s" % file('VMExpress_Dev10_DirectXSDK', payloads))
  system("start /wait msiexec.exe /i %s" % file('VMExpress_Dev10_xde2x64', payloads))
  system("start /wait msiexec.exe /i %s" % file('VMExpress_Dev10_WPSDK', payloads))
  system("start /wait msiexec.exe /i %s /passive" % file('silverlight4_SDK', payloads))
  system("start /wait msiexec.exe /i %s" % file('PortableLibrary_DTP', payloads))
  system("start /wait msiexec.exe /i %s" % file('PortableLibrary_DTP_LP', payloads))
  system("start /wait msiexec.exe /i %s" % file('sdk_tools35', payloads))
  system("start /wait msiexec.exe /i %s" % file('sdk_tools4', payloads))
  system("start /wait msiexec.exe /i %s /passive" % file('VMExpress_AdSdk', payloads))
  system("start /wait msiexec.exe /i %s" % file('VMExpress_ProfilerARM', payloads))
  system("start /wait msiexec.exe /i %s" % file('VMExpress_ProfilerX86', payloads))
  system("start /wait msiexec.exe /i %s" % file('Blend_Core', payloads))
  system("start /wait msiexec.exe /i %s" % file('Blend_LP', payloads))
  system("start /wait msiexec.exe /p %s" % file('msp_kb2744908', payloads))
  system("start /wait msiexec.exe /i %s /passive" % file('BlendSDKForWindowsPhone80', payloads))
  system("start /wait msiexec.exe /i %s /passive" % file('BlendFXGAddin', payloads))
  system("start /wait msiexec.exe /i %s /passive" % file('BlendSDKForWindowsPhone7', payloads))
  system("start /wait msiexec.exe /i %s /passive" % file('BlendSDKForWindowsPhone71', payloads))
  system("start /wait msiexec.exe /i %s" % file('Bliss_Core', payloads))
  system("start /wait msiexec.exe /i %s" % file('Bliss_LP', payloads))
  system("start /wait msiexec.exe /p %s" % file('msp_kb2720192', payloads))
  system("start /wait msiexec.exe /i %s" % file('nugetvpd2012', payloads))
  #system("start /wait %s" % file('silverlight5_DRT', payloads))
  #system("start /wait msiexec.exe /i %s" % file('Preparation', payloads))
  #system("start /wait msiexec.exe /i %s" % file('vs_postclean_WPexpress', payloads))
  system("start /wait msiexec.exe /i %s" % file('WPexpress_finalizer', payloads))
  system("start /wait msiexec.exe /i %s" % file('MobileTools_XDEConfig', payloads))
  system("start /wait msiexec.exe /i %s" % file('MobileTools_Finalizer', payloads))
end
